import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Footer from '../components/Footer'
import Link from 'next/link'

export default function Index() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>

        <h1 className={styles.title}>
          Welcome to Battlemon
        </h1>

        <p className={styles.description}>
          Get started with Sui Blockhain
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <Link href="/home" className={styles.card}>
            <h2>Home &rarr;</h2>
            <p>Learn about Battlemon in an interactive scene!</p>
          </Link>

          <Link href="/hub" className={styles.card}>
            <h2>Hub &rarr;</h2>
            <p>Find in-depth information about our Hub.</p>
          </Link>

          <Link
            href="/newlemon"
            className={styles.card}
          >
            <h2>Test Lemon &rarr;</h2>
            <p>Scene with placeholders and animations.</p>
          </Link>

          <Link
            href="/"
            className={styles.card}
          >
            <h2>Marketplace &rarr;</h2>
            <p>Discover Battlemon marketplace.</p>
          </Link>

          <Link
            href="/"
            className={styles.card}
          >
            <h2>History &rarr;</h2>
            <p>
              Instantly view transactions history.
            </p>
          </Link>
        </div>
      </main>

      <Footer />
    </div>
  )
}
