import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/header'
import Link from 'next/link'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>

        <h1 className={styles.title}>
          Welcome to Battlemon
        </h1>

        <p className={styles.description}>
          Get started with Sui Blockhain
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <Link href="/hub" className={styles.card}>
            <h2>Hub &rarr;</h2>
            <p>Find in-depth information about our Hub.</p>
          </Link>

          <Link href="/" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Battlemon in an interactive scene!</p>
          </Link>

          <Link
            href="/"
            className={styles.card}
          >
            <h2>Marketplace &rarr;</h2>
            <p>Discover Battlemon marketplace.</p>
          </Link>

          <Link
            href="/"
            className={styles.card}
          >
            <h2>History &rarr;</h2>
            <p>
              Instantly view transactions history.
            </p>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
